# Generated by Django 3.1.2 on 2020-11-19 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=3000, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(2, 'Cancel'), (1, 'Reviewed'), (0, 'Pending')], null=True)),
                ('review', models.CharField(blank=True, max_length=3000, null=True)),
                ('is_seen', models.BooleanField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complaint',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('number_of_days', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(2, 'Rejected'), (1, 'Approved'), (0, 'Pending')], null=True)),
                ('purpose', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_days', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_days_used', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_days_left', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'staff',
                'get_latest_by': 'created_at',
            },
        ),
    ]
