# Generated by Django 3.1.2 on 2020-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Cancel'), (0, 'Pending'), (1, 'Reviewed')], null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Approved'), (0, 'Pending'), (2, 'Rejected')], null=True),
        ),
    ]
