# Generated by Django 3.1.2 on 2020-11-19 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_id', models.CharField(max_length=255, unique=True)),
                ('user_type', models.CharField(blank=True, choices=[('SU', 'Support'), ('MU', 'Manager'), ('AD', 'Administrator'), ('NU', 'Normal Staff')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Dismissed', 'Dismissed'), ('Suspended', 'Suspended'), ('On Leave', 'On Leave')], max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('HM', 'Hospital Manager'), ('DR', 'Doctor'), ('IT', 'IT'), ('CH', 'Cashier'), ('NRS', 'Nurse'), ('HR', 'Human Resource'), ('ACC', 'Accountant'), ('PHM', 'Pharmacist')], max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ('staff_id', 'date_joined'),
            },
        ),
    ]
