# Generated by Django 3.1.2 on 2020-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('NRS', 'Nurse'), ('IT', 'IT'), ('HR', 'Human Resource'), ('ACC', 'Accountant'), ('PHM', 'Pharmacist'), ('HM', 'Hospital Manager'), ('DR', 'Doctor'), ('CH', 'Cashier')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Dismissed', 'Dismissed'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended'), ('Active', 'Active')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AD', 'Administrator'), ('SU', 'Support'), ('NU', 'Normal Staff'), ('MU', 'Manager')], max_length=255, null=True),
        ),
    ]
