# Generated by Django 3.1.2 on 2020-11-19 12:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bill_type', models.CharField(blank=True, choices=[('WB', 'Ward Bills'), ('CB', 'Card Bills'), ('CnB', 'Consultation Bills'), ('PB', 'Procedures Bills'), ('PhB', 'Pharmacy Bills'), ('LB', 'Lab Bills')], max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Paid'), (0, 'Not Paid')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='DefaultBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(blank=True, choices=[('WB', 'Ward Bills'), ('CB', 'Card Bills'), ('CnB', 'Consultation Bills'), ('PB', 'Procedures Bills'), ('PhB', 'Pharmacy Bills'), ('LB', 'Lab Bills')], max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'default_bill',
                'ordering': ('-created_at',),
            },
        ),
    ]
