# Generated by Django 3.1.2 on 2020-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20201119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PhB', 'Pharmacy Bills'), ('CnB', 'Consultation Bills'), ('WB', 'Ward Bills'), ('CB', 'Card Bills'), ('PB', 'Procedures Bills'), ('LB', 'Lab Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultbill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PhB', 'Pharmacy Bills'), ('CnB', 'Consultation Bills'), ('WB', 'Ward Bills'), ('CB', 'Card Bills'), ('PB', 'Procedures Bills'), ('LB', 'Lab Bills')], max_length=100, null=True),
        ),
    ]
