# Generated by Django 3.1.2 on 2020-11-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_auto_20201119_1222'),
        ('staff', '0001_initial'),
        ('management', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_incharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ward',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='ward_patients', to='management.Patient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_diagnosis', to='management.medicaldiagnosis'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='pharmacy_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_prescription', to='pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_bill', to='portal.bill'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenue',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_patient', to='management.patient'),
        ),
        migrations.AddField(
            model_name='request',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_bed', to='management.bed'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, related_name='patient_diagnoses', to='management.MedicalDiagnosis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='patient_notes', to='department.Note'),
        ),
        migrations.AddField(
            model_name='medicaldiagnosis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldiagnosis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_patient', to='management.patient'),
        ),
        migrations.AddField(
            model_name='medicaldiagnosis',
            name='treatments',
            field=models.ManyToManyField(blank=True, related_name='diagnosis_treatments', to='management.Treatment'),
        ),
        migrations.AddField(
            model_name='leaveperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveperiod',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='leave_period_staffs', to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocate_bed', to='management.bed'),
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocate_patient', to='management.patient'),
        ),
        migrations.AddField(
            model_name='bed',
            name='allocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocate', to='management.bedallocate'),
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_allocates',
            field=models.ManyToManyField(blank=True, related_name='bed_bed_allocates', to='management.BedAllocate'),
        ),
        migrations.AddField(
            model_name='bed',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_ward', to='management.ward'),
        ),
    ]
