# Generated by Django 3.1.2 on 2020-11-19 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine_type', models.CharField(blank=True, choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Capsule', 'Capsule')], max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_in_box', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_price_per_box', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('accumulated_boxes_bought', models.IntegerField(blank=True, default=0, null=True)),
                ('boxes_bought', models.IntegerField(blank=True, default=0, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('accumulated_total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('selling_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price_per_box', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sold_units', models.IntegerField(blank=True, default=0, null=True)),
                ('sold_boxes', models.IntegerField(blank=True, default=0, null=True)),
                ('total_sales', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('units_left', models.IntegerField(blank=True, default=0, null=True)),
                ('boxes_left', models.IntegerField(blank=True, default=0, null=True)),
                ('total_no_units_accumulated', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=2000, null=True)),
                ('frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'prescribed_medicine',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Confirmed'), (0, 'Pending')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
